### ISSUE TITLE
inconsistent ftp path correction in file transfer api

### ISSUE THREAD

**Issue by smithedl** [NISystemsEngineering/SystemManagementAndInformation#3]
Some of the functions (like put) use the fix path function to fix the remote path
others (like delete) do not. It would make sense to pick one or the other.

Cant confirm if this is still the case here, as I don't have 2015 yet, but I'm guessing it is.

**Comment by leesecho** [comment]
The File Transfer API, as with all currently unused RT Management.lvlib member VIs, was removed from SMI. It was determined that the current scope of SMI should not include this feature. I will discuss the potential of future inclusion of the File Transfer API in SMI, or a separate SE reuse library based on its features. A "Green Light" for such a project would depend mostly on customer need (current users of RT Management.lvlib, etc. who use the palette).
