### ISSUE TITLE
File transfer behavior depends on lv version as well as OS

### ISSUE THREAD

**Issue by smithedl** [NISystemsEngineering/SystemManagementAndInformation#4]
RT Management\classes\RT Management\Initialize File Transfer Behavior.vi
In newer lv versions users have to manually install the FTP server while webdav is installed automatically, even on vxworks targets. Not sure if this is something that is worth fixing, though.

**Comment by leesecho** [comment]
The File Transfer API, as with all currently unused RT Management.lvlib member VIs, was removed from SMI. (See closed Issue #3).
