### ISSUE TITLE
webdav create directory mishandles prefixes

### ISSUE THREAD

**Issue by smithedl** [NISystemsEngineering/SystemManagementAndInformation#5]
RT Management\classes\WebDAV\Create directory.vi called by RT Management\classes\WebDAV\Put file.vi called by RT Management\classes\RT Management\Modify RT INI.vi

If you pass in a path like http://IP/files/blah.txt it attempts to create /http:, /http://IP, /http://IP/files. It can't create any of these so an error is generated, which is right.

**Comment by smithedl** [comment]
My fix was to add this check to the start of the create dir function, that way its inside of just the webdav class
![fix](https://cloud.githubusercontent.com/assets/16479354/12042488/7ebe2186-ae30-11e5-9657-7e27a85f14b0.png)

**Comment by leesecho** [comment]
The File Transfer API, as with all currently unused RT Management.lvlib member VIs, was removed from SMI. Issue reports for the File Transfer API will be collected from this thread, should support of the features be adopted (See closed Issue #3).
